name: Deploy to Railway

on:
  workflow_run:
    workflows: ["Validate API"]
    types:
        - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container: ghcr.io/railwayapp/cli:latest
    env:
      SVC_ID: 8385f83c-b69f-4ff5-8869-d947427e1e2c
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: railway up --service=${{ env.SVC_ID }}