# Generated by Django 6.0.5 on 2026-08-16 00:55

import django.db.models.deletion
import phonenumber_field.modelfields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text="Client's first name", max_length=20)),
                ('last_name', models.CharField(help_text="Client's last name", max_length=20)),
                ('city', models.CharField(help_text='City where client is located', max_length=20)),
                ('state', models.CharField(help_text='State abbreviation (e.g., CA, NY)', max_length=2)),
                ('zip_code', models.CharField(help_text="Postal code for client's address", max_length=20)),
                ('email', models.EmailField(help_text="Client's email address for contact", max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text="Client's phone number", max_length=128, region=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who owns this client', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(help_text='Name of the project', max_length=20)),
                ('project_type', models.CharField(choices=[('event', 'Event'), ('portrait', 'Portrait'), ('party', 'Party')], default='event', help_text='Type of project (event, portrait, or party)', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(help_text='Client associated with this project', on_delete=django.db.models.deletion.CASCADE, to='fstop.client')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gallery_name', models.CharField(help_text='Name of the gallery', max_length=50)),
                ('picture_count', models.IntegerField(help_text='Number of pictures in the gallery')),
                ('is_visible', models.BooleanField(help_text='Whether the gallery is publicly visible')),
                ('url', models.URLField(help_text='URL link to the gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project associated with this gallery', on_delete=django.db.models.deletion.CASCADE, to='fstop.project')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date of the booking')),
                ('time', models.TimeField(help_text='Time of the booking')),
                ('duration', models.IntegerField(help_text='Booking duration in minutes')),
                ('location', models.CharField(help_text='Booking location', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(help_text='Project associated with this booking', on_delete=django.db.models.deletion.CASCADE, to='fstop.project')),
            ],
        ),
    ]
