# Generated by Django 6.0.5 on 2026-05-21 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstop', '0002_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
