# Generated by Django 6.0.5 on 2026-05-21 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstop', '0004_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_name',
            field=models.CharField(max_length=50),
        ),
    ]
