# Generated by Django 6.0.5 on 2026-05-25 01:16

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fstop', '0005_alter_gallery_gallery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(help_text='Date of the booking'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(help_text='Booking duration in minutes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='location',
            field=models.CharField(help_text='Booking location', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='project',
            field=models.ForeignKey(help_text='Project associated with this booking', on_delete=django.db.models.deletion.CASCADE, to='fstop.project'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.TimeField(help_text='Time of the booking'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(help_text='City where client is located', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(help_text="Client's email address for contact", max_length=254),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(help_text="Client's first name", max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(help_text="Client's last name", max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text="Client's phone number", max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(help_text='State abbreviation (e.g., CA, NY)', max_length=2),
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.CharField(help_text="Postal code for client's address", max_length=20),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_name',
            field=models.CharField(help_text='Name of the gallery', max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_visible',
            field=models.BooleanField(help_text='Whether the gallery is publicly visible'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='picture_count',
            field=models.IntegerField(help_text='Number of pictures in the gallery'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='project',
            field=models.ForeignKey(help_text='Project associated with this gallery', on_delete=django.db.models.deletion.CASCADE, to='fstop.project'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='url',
            field=models.URLField(help_text='URL link to the gallery'),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(help_text='Client associated with this project', on_delete=django.db.models.deletion.CASCADE, to='fstop.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(help_text='Name of the project', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('event', 'Event'), ('portrait', 'Portrait'), ('party', 'Party')], default='event', help_text='Type of project (event, portrait, or party)', max_length=8),
        ),
    ]
